server:
  port: 10000

spring:
  application:
    name: fancy-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:7000
      client:
        registration:
          fan:
            provider: authorization-server
            client-id: fancy-gateway
            client-secret: 123456
            authorization-grant-type: authorization_code
            scope: openid,profile,fan
        provider:
          authorization-server:
            issuer-uri: http://127.0.0.1:7000
  cloud:
    nacos:
      server-addr: 1.12.253.22:8848
      username: nacos
      password: fan223
    gateway:
      server:
        webflux:
          default-filters:
            - TokenRelay
            - StripPrefix=1
          routes:
            - id: resource
              uri: lb://resource
              predicates:
                - Path=/resource/**